version: "3.3"
services:

  client:
    build:
      context: ../client/
      dockerfile: ./deploy/client/Dockerfile
    network_mode: "host"
    depends_on:
      - server

  server:
    build:
      context: ../server
      dockerfile: ./deploy/server/Dockerfile
    network_mode: "host"
    depends_on:
      - migration

  migration:
    build:
      context: ../
      dockerfile: ../server/deploy/migration/Dockerfile
    network_mode: "host"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aA123456}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    network_mode: "host"


volumes:
  postgres:
  pgadmin:
